version: '3.8'
services:
  frontend:
    build:
      context: ./End_to_End_Frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - devops-network
    restart: always  # Ensure the container always restarts if it stops

  backend:
    build:
      context: ./end_to_end_Backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/mydatabase
    depends_on:
      - db
    networks:
      - devops-network
    volumes:
      - backend-data:/app/data
    restart: always  # Ensure the container always restarts if it stops

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - devops-network
    restart: always  # Ensure the container always restarts if it stops

networks:
  devops-network:
    driver: bridge

volumes:
  db-data:
    driver: local
  backend-data:
    driver: local

