services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: mydatabase
    depends_on:
      - db
    restart: always  # Restart policy

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always  # Restart policy

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mydatabase
    volumes:
      - db_data:/var/lib/mysql
    restart: always  # Restart policy

volumes:
  db_data:
